deploy/objects/Candidate__c.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

deploy/classes/AddContact_Test.cls
@isTest
public class AddContact_Test {
    static testMethod void positive_TestOneCandidate(){
        Candidate__c cand = new Candidate__c(First_Name__c = 'Test', Last_Name__c='Candidato0');
        database.insert(cand);
        Contact ctct = [SELECT FirstName, LastName
                       FROM Contact
                       WHERE FirstName ='Test' AND LastName='Candidato0'];
        System.assert(ctct.FirstName == cand.First_Name__c);
        System.assert(ctct.LastName == cand.Last_Name__c);
    }

}