deploy/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Broker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Broker</label>
        <referenceTo>Broker__c</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>Properties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Listed__c</fullName>
        <label>Date Listed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Days_On_Market__c</fullName>
        <formula>TODAY() - Date_Listed__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Days On Market</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

deploy/classes/PropertyUtility.cls
public class PropertyUtility {
    public static void newListedProperties(){

        list<Property__c> newPropList = [select Name,broker__r.email__c,days_on_market__C from property__c where Date_Listed__c = LAST_N_DAYS:30 ];

        for(Property__c Prop : newPropList)
        {
            string propEmail = 'Property Name: '+Prop.Name+',Broker Email: ' +Prop.Broker__r.email__c ; 
            system.debug(propEmail);
        }

    }

}